<?php
declare(strict_types=1);
$usersBaseUrl = $adminUrl . '?section=users';
?>
<div class="panel-intro"><div><p class="panel-eyebrow">Zákazníci</p><h1>Uživatelské účty</h1><p>Hledej podle jména nebo e-mailu, uprav údaje a přístup k účtu. Objednávky zůstávají uložené i u zablokovaného účtu.</p></div></div>
<?php if ($usersError !== ''): ?><p class="panel-error" role="alert"><?= $escape($usersError) ?></p><?php endif; ?>
<?php if (($_GET['saved'] ?? '') === '1'): ?><p class="panel-notice" role="status">Změna zákazníka byla uložena.</p><?php endif; ?>
<?php if ($customer !== null): ?>
  <section class="panel-panel"><h2><?= $escape($customer['display_name']) ?></h2><p><?= $escape($customer['email']) ?> · <?= (int) $customer['order_count'] ?> objednávek · <?= (int) $customer['address_count'] ?> adres · <?= (int) $customer['is_active'] === 1 ? 'Aktivní' : 'Zablokovaný' ?></p>
    <form class="panel-form" method="post" action="<?= $escape($usersBaseUrl . '&id=' . (int) $customer['id']) ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="action" value="customer-update"><input type="hidden" name="id" value="<?= (int) $customer['id'] ?>">
      <label>Jméno<input name="display_name" value="<?= $escape($customer['display_name']) ?>" maxlength="120" required></label><label>E-mail<input type="email" name="email" value="<?= $escape($customer['email']) ?>" maxlength="254" required></label><label>Telefon<input type="tel" name="phone" value="<?= $escape($customer['phone']) ?>" maxlength="40"></label><button class="panel-button" type="submit">Uložit údaje</button>
    </form>
    <form class="panel-form" method="post" action="<?= $escape($usersBaseUrl . '&id=' . (int) $customer['id']) ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="action" value="customer-active"><input type="hidden" name="id" value="<?= (int) $customer['id'] ?>"><input type="hidden" name="active" value="<?= (int) $customer['is_active'] === 1 ? '0' : '1' ?>"><button class="panel-button" type="submit"><?= (int) $customer['is_active'] === 1 ? 'Zablokovat přihlášení' : 'Povolit přihlášení' ?></button></form>
    <form class="panel-form" method="post" action="<?= $escape($usersBaseUrl . '&id=' . (int) $customer['id']) ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="action" value="customer-password"><input type="hidden" name="id" value="<?= (int) $customer['id'] ?>"><label>Nastavit nové heslo<input type="password" name="password" minlength="12" autocomplete="new-password" required></label><button class="panel-button" type="submit">Změnit heslo</button><p class="panel-help">Předchozí přihlášení zákazníka tím skončí. Nové heslo mu předej bezpečnou cestou.</p></form>
  </section>
<?php endif; ?>
<section class="panel-panel"><h2>Seznam zákazníků</h2>
  <form class="panel-search" method="get" action="<?= $escape($adminUrl) ?>"><input type="hidden" name="section" value="users"><label>Hledat jméno nebo e-mail <input type="search" name="search" value="<?= $escape($search) ?>" maxlength="100"></label><button class="panel-button" type="submit">Hledat</button></form>
  <?php if ($usersPage['items'] === []): ?><p class="panel-empty">Žádný zákazník neodpovídá hledání.</p><?php endif; ?>
  <div class="panel-order-list"><?php foreach ($usersPage['items'] as $listed): ?><a class="panel-order-row" href="<?= $escape($usersBaseUrl . '&id=' . (int) $listed['id']) ?>"><span><strong><?= $escape($listed['display_name']) ?></strong><small><?= $escape($listed['email']) ?></small></span><span><?= (int) $listed['order_count'] ?> objednávek</span><span><?= (int) $listed['is_active'] === 1 ? 'Aktivní' : 'Zablokovaný' ?></span><strong>Upravit →</strong></a><?php endforeach; ?></div>
  <div class="panel-order-pages"><?php if ($offset > 0): ?><a href="<?= $escape($usersBaseUrl . '&search=' . rawurlencode($search) . '&offset=' . max(0, $offset - 25)) ?>">← Předchozí</a><?php endif; ?><?php if ($usersPage['nextOffset'] !== null): ?><a href="<?= $escape($usersBaseUrl . '&search=' . rawurlencode($search) . '&offset=' . $usersPage['nextOffset']) ?>">Další →</a><?php endif; ?></div>
</section>
<section class="panel-panel"><h2>Vytvořit zákazníka</h2><p class="panel-help">Zákazník se může registrovat i sám. Při ručním založení mu předej heslo bezpečnou cestou.</p><form class="panel-form" method="post" action="<?= $escape($usersBaseUrl) ?>"><input type="hidden" name="csrf" value="<?= $escape($csrf) ?>"><input type="hidden" name="action" value="customer-create"><label>Jméno<input name="display_name" maxlength="120" required></label><label>E-mail<input type="email" name="email" maxlength="254" required></label><label>Počáteční heslo<input type="password" name="password" minlength="12" autocomplete="new-password" required></label><button class="panel-button" type="submit">Vytvořit účet</button></form></section>
