#!/usr/bin/env python3
"""Build an idempotent MySQL seed from the reviewed Czech terms draft."""

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/obchodni-podminky.md"
DESTINATION = ROOT / "database/seed-legal-pages.sql"
PAGES = [
    ("doprava-a-platba", "Doprava a platba", "Přehled doručení a způsobů platby.",
     "[DOPLNIT PODLE SKUTEČNÉ NABÍDKY POKLADNY: dopravci, výdejní místa, dobírka, ceny, lhůty a platební metody.]"),
    ("vymena-a-vraceni-zbozi", "Výměna a vrácení zboží", "Odstoupení od smlouvy a případná výměna.",
     "[DOPLNIT ADRESU PRO VRÁCENÍ, KONTAKT A PŘÍPADNÁ PRAVIDLA DOBROVOLNÉ VÝMĚNY. Zákonné odstoupení upravují obchodní podmínky.]"),
    ("obchodni-podminky", "Obchodní podmínky", "Pravidla nákupu u dobrodruzi s.r.o.", None),
    ("reklamacni-rad", "Reklamační řád", "Jak uplatnit práva z vadného plnění.",
     "[DOPLNIT FUNKČNÍ KONTAKT, ADRESU PRO REKLAMACE A POSTUP PRO VYDÁNÍ POTVRZENÍ. Zákonná práva upravují obchodní podmínky.]"),
    ("ochrana-osobnich-udaju", "Ochrana osobních údajů", "Informace o zpracování osobních údajů.",
     "[DOPLNIT SAMOSTATNÉ INFORMACE DLE SKUTEČNÉHO ZPRACOVÁNÍ OSOBNÍCH ÚDAJŮ; TENTO KONCEPT NENÍ HOTOVOU GDPR INFORMACÍ.]"),
    ("kontakt", "Kontakt", "Jak se spojit s dobrodruzi s.r.o.",
     "[DOPLNIT NÁZEV, SÍDLO, IČO, KONTAKTNÍ E-MAIL, TELEFON A ADRESU PRO VRÁCENÍ ZBOŽÍ A REKLAMACE.]"),
]


def sections_from_markdown(source: str) -> list[dict[str, str]]:
    sections = []
    heading = None
    body = []
    for line in source.splitlines():
        if line.startswith("## "):
            if heading is not None:
                sections.append({"type": "text", "heading": heading, "body": "\n".join(body).strip()})
            heading = line[3:]
            body = []
        elif heading is not None:
            body.append(line)
    if heading is not None:
        sections.append({"type": "text", "heading": heading, "body": "\n".join(body).strip()})
    assert len(sections) == 12 and all(section["body"] for section in sections)
    return sections


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_utf8(value: str) -> str:
    # A hex literal also works with NO_BACKSLASH_ESCAPES and keeps all Czech text intact.
    return "CONVERT(0x" + value.encode("utf-8").hex() + " USING utf8mb4)"


terms = sections_from_markdown(SOURCE.read_text(encoding="utf-8"))
queries = [
    "-- Import after database/schema.sql; existing pages and revisions are never overwritten.",
    "-- All six pages are drafts. Fill [DOPLNIT ...] in CMS, then publish each page.",
    "-- The footer shows each link only after its page is published.",
    "-- Generated by scripts/build-legal-sql.py from docs/obchodni-podminky.md.",
    "START TRANSACTION;",
]
for slug, title, summary, placeholder in PAGES:
    sections = terms if placeholder is None else [{"type": "text", "heading": "K doplnění", "body": placeholder}]
    body = json.dumps({"format": "simple-store-blocks-v1", "sections": sections}, ensure_ascii=False, separators=(",", ":"))
    key = hashlib.md5(("dobrodruzi:legal:" + slug).encode("utf-8")).hexdigest()
    queries.append(
        "\n-- " + title + "\n"
        "INSERT INTO content_revisions\n"
        "  (document_key, active_document_key, language, revision_number, type, slug, active_slug,\n"
        "   title, summary, body, published, visible_in_menu, menu_order)\n"
        f"SELECT '{key}', '{key}', 'cs', 1, 'page', '{slug}', '{slug}',\n"
        f"       {sql_string(title)}, {sql_string(summary)}, {sql_utf8(body)}, 0, 0, 0\n"
        "WHERE NOT EXISTS (SELECT 1 FROM content_revisions WHERE type='page' AND language='cs'\n"
        f"  AND active_slug='{slug}')\n"
        "  AND NOT EXISTS (SELECT 1 FROM content_revisions WHERE document_key='" + key + "' AND language='cs');"
    )
queries.append("\nCOMMIT;\n")
DESTINATION.write_text("\n".join(queries), encoding="utf-8")
print(DESTINATION)
